[package]
name = "funwolf7/chlorine"
description = "Fixes some bugs with Chlorine. Not really intended to be used by others, but go ahead I guess. "
version = "0.0.4"
license = "MIT"
authors = ["Hexcede", "funwolf7"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]


[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"